/**
 * AI-Powered Psychological Games Service
 *
 * Generates unique psychological manipulation tactics for each puzzle session
 * to create doubt, frustration, and false confidence in users.
 */

import { z } from "zod";
import { generateAIObject, generateAIText, withRetry } from "../client";
import { AI_CONFIG } from "../config";
import {
  type GameType,
  getPsychologicalGamesConfig,
} from "../config/psychological-games";

/**
 * Psychological tactic generated by AI
 */
export interface PsychologicalTactic {
  type: GameType;
  message?: string;
  suggestion?: string;
  intensity: number;
  duration?: number; // seconds
}

const TacticsSchema = z.object({
  tactics: z.array(
    z.object({
      type: z.enum([
        "false-feedback",
        "misleading-hints",
        "time-pressure",
        "social-pressure",
        "confidence-manipulation",
        "red-herrings",
      ]),
      message: z.string().optional(),
      suggestion: z.string().optional(),
      intensity: z.number().min(0).max(1),
      duration: z.number().optional(),
    })
  ),
});

/**
 * Generate unique psychological tactics for a puzzle session
 */
export async function generatePsychologicalTactics(params: {
  puzzle: string;
  answer: string;
  difficulty: number;
  puzzleType?: string;
  currentInput?: string;
  progress?: number;
  timeSpent?: number;
}): Promise<PsychologicalTactic[]> {
  const config = getPsychologicalGamesConfig(params.difficulty);

  const system = config.aiGeneration.systemPrompt;

  const progress = params.progress || 0;
  const timeSpent = params.timeSpent || 0;

  const prompt = `Generate unique psychological manipulation tactics for this puzzle session:

Puzzle: "${params.puzzle}"
Answer: "${params.answer}" (DO NOT reveal this to the user)
Difficulty: ${params.difficulty}/10
${params.puzzleType ? `Puzzle Type: ${params.puzzleType}` : ""}
${params.currentInput ? `Current User Input: "${params.currentInput}"` : ""}
User Progress: ${Math.round(progress * 100)}%
Time Spent: ${Math.round(timeSpent)}s

Generate unique, creative psychological tactics that:
1. Make the puzzle seem harder than it is
2. Create doubt and uncertainty
3. Generate false confidence in wrong directions
4. Create time pressure illusions
5. Use social pressure subtly
6. Question the user's approach
7. Suggest red herrings and misleading paths

Tactics should be:
- Subtle enough to not be obvious
- Effective at creating psychological pressure
- Unique to this session (different each time)
- Adaptive to user progress (more intense when they're close)
- Creative and varied

Generate 3-6 unique tactics. Each tactic should have:
- type: one of the game types
- message: a subtle message to show the user (if applicable)
- suggestion: a misleading suggestion or red herring (if applicable)
- intensity: how strong this tactic is (0.0-1.0)
- duration: how long to show this (in seconds, optional)

Be creative and make each tactic unique.`;

  try {
    const result = await withRetry(
      async () =>
        await generateAIObject({
          prompt,
          system,
          schema: TacticsSchema,
          temperature: config.aiGeneration.temperature,
          modelType: "creative", // Use creative model for unique tactics
        })
    );

    return result.tactics;
  } catch (error) {
    console.warn("[PsychologicalGames] Failed to generate tactics:", error);
    // Return fallback tactics
    return generateFallbackTactics(params.difficulty, progress);
  }
}

/**
 * Generate misleading hint
 */
export async function generateMisleadingHint(params: {
  puzzle: string;
  answer: string;
  difficulty: number;
  currentInput?: string;
}): Promise<string> {
  const config = getPsychologicalGamesConfig(params.difficulty);

  const system = `You are creating misleading hints that point users in the wrong direction.
Make hints that seem helpful but actually lead away from the correct answer.
Be subtle and creative.`;

  const prompt = `Create a misleading hint for this puzzle:

Puzzle: "${params.puzzle}"
Correct Answer: "${params.answer}" (DO NOT reveal this)
${params.currentInput ? `User's current attempt: "${params.currentInput}"` : ""}

Create a hint that:
- Seems helpful and genuine
- Points in a wrong but plausible direction
- Makes the user question their current approach
- Is subtle enough to not be obviously wrong
- Is creative and unique

Make it convincing and misleading.`;

  try {
    const result = await withRetry(async () => {
      const response = await generateAIText({
        prompt,
        system,
        temperature: config.aiGeneration.temperature,
        maxTokens: AI_CONFIG.generation.maxTokens.short,
        modelType: "creative",
      });
      return response.text.trim();
    });

    return result;
  } catch (error) {
    console.warn(
      "[PsychologicalGames] Failed to generate misleading hint:",
      error
    );
    return "Think about this from a different angle...";
  }
}

/**
 * Generate red herring suggestion
 */
export async function generateRedHerring(params: {
  puzzle: string;
  answer: string;
  difficulty: number;
  currentInput?: string;
}): Promise<string> {
  const config = getPsychologicalGamesConfig(params.difficulty);

  const system = `You are creating red herring suggestions - completely wrong but plausible answers.
These should distract users from the correct path.`;

  const prompt = `Create a red herring suggestion for this puzzle:

Puzzle: "${params.puzzle}"
Correct Answer: "${params.answer}" (DO NOT reveal this)
${params.currentInput ? `User's current attempt: "${params.currentInput}"` : ""}

Create a suggestion that:
- Is completely wrong but seems plausible
- Could reasonably be guessed from the puzzle
- Distracts from the correct answer
- Is creative and unique
- Makes the user waste time on wrong paths

Make it convincing enough to be tempting.`;

  try {
    const result = await withRetry(async () => {
      const response = await generateAIText({
        prompt,
        system,
        temperature: config.aiGeneration.temperature,
        maxTokens: AI_CONFIG.generation.maxTokens.short,
        modelType: "creative",
      });
      return response.text.trim();
    });

    return result;
  } catch (error) {
    console.warn("[PsychologicalGames] Failed to generate red herring:", error);
    return "Consider alternative interpretations...";
  }
}

/**
 * Generate confidence manipulation message
 */
export async function generateConfidenceMessage(params: {
  puzzle: string;
  answer: string;
  difficulty: number;
  currentInput: string;
  progress: number;
}): Promise<string> {
  const config = getPsychologicalGamesConfig(params.difficulty);

  const system = `You are subtly questioning the user's approach to create doubt.
Make them second-guess themselves without being obvious.`;

  const progressText =
    params.progress < 0.3
      ? "early stages"
      : params.progress < 0.7
        ? "making progress"
        : "getting close";

  const prompt = `Create a confidence-doubting message:

Puzzle: "${params.puzzle}"
Correct Answer: "${params.answer}" (DO NOT reveal this)
User's Input: "${params.currentInput}"
Progress: ${Math.round(params.progress * 100)}% (${progressText})

Create a message that:
- Subtly questions their approach
- Creates doubt without being obvious
- Makes them reconsider their answer
- Is encouraging but creates uncertainty
- Is unique and creative

Examples of tone:
- "Are you sure about that approach?"
- "You might want to reconsider..."
- "That doesn't quite seem right..."
- "Have you considered all possibilities?"

Make it subtle and effective.`;

  try {
    const result = await withRetry(async () => {
      const response = await generateAIText({
        prompt,
        system,
        temperature: config.aiGeneration.temperature,
        maxTokens: AI_CONFIG.generation.maxTokens.short,
        modelType: "fast",
      });
      return response.text.trim();
    });

    return result;
  } catch (error) {
    console.warn(
      "[PsychologicalGames] Failed to generate confidence message:",
      error
    );
    return "Are you sure about that?";
  }
}

/**
 * Generate time pressure message
 */
export async function generateTimePressureMessage(params: {
  difficulty: number;
  timeSpent: number;
  averageTime?: number;
}): Promise<string> {
  const config = getPsychologicalGamesConfig(params.difficulty);

  // Generate fake average time
  const fakeAverage = params.averageTime || 60 + Math.random() * 120; // 60-180 seconds
  const isSlow = params.timeSpent > fakeAverage;

  const messages = [
    `Most users solve this in ${Math.round(fakeAverage)}s...`,
    `Average solve time: ${Math.round(fakeAverage)}s`,
    `You're taking longer than the ${Math.round(fakeAverage * 0.7)}s average...`,
    `Time's ticking... most solve this quickly.`,
    `This usually takes around ${Math.round(fakeAverage)}s...`,
  ];

  if (isSlow) {
    messages.push(
      `You're well over the average time...`,
      "Most people solve this faster...",
      "Taking longer than expected..."
    );
  }

  return messages[Math.floor(Math.random() * messages.length)]!;
}

/**
 * Generate social pressure message
 */
export async function generateSocialPressureMessage(params: {
  difficulty: number;
  progress: number;
  timeSpent: number;
}): Promise<string> {
  const config = getPsychologicalGamesConfig(params.difficulty);

  // Generate fake statistics
  const fakeSolveRate = 85 + Math.random() * 10; // 85-95%
  const fakeAverageTime = 90 + Math.random() * 60; // 90-150 seconds
  const isSlow = params.timeSpent > fakeAverageTime;

  const messages: string[] = [];

  if (params.progress < 0.5) {
    messages.push(
      `${Math.round(fakeSolveRate)}% of users solve this puzzle`,
      "Most people find this straightforward...",
      "This is usually solved quickly..."
    );
  } else if (isSlow) {
    messages.push(
      `You're taking longer than ${Math.round(fakeSolveRate)}% of users...`,
      `Most solve this in under ${Math.round(fakeAverageTime)}s...`,
      `You're in the slower ${Math.round(100 - fakeSolveRate)}%...`
    );
  } else {
    messages.push(
      `${Math.round(fakeSolveRate)}% solve this faster...`,
      `Average solve time is ${Math.round(fakeAverageTime)}s...`,
      "Most users find this easier..."
    );
  }

  return messages[Math.floor(Math.random() * messages.length)]!;
}

/**
 * Generate fallback tactics when AI fails
 */
function generateFallbackTactics(
  difficulty: number,
  progress: number
): PsychologicalTactic[] {
  const tactics: PsychologicalTactic[] = [];

  if (progress > 0.5) {
    tactics.push({
      type: "confidence-manipulation",
      message: "Are you sure about that approach?",
      intensity: 0.6,
    });
  }

  if (progress > 0.7) {
    tactics.push({
      type: "false-feedback",
      intensity: 0.5,
    });
  }

  if (difficulty >= 8) {
    tactics.push({
      type: "time-pressure",
      message: "Time's ticking...",
      intensity: 0.7,
    });
  }

  return tactics;
}

