/**
 * Persist a full Eve-generated blog post for a puzzle into MongoDB.
 * Used by midnight workflow + 20:00 blog cron so fields stay consistent.
 */

import { revalidateTag } from "next/cache";
import { generateBlogPost } from "@/ai/services/blog-generator";
import type { BlogArchiveDate, BlogPost, NewBlogPost, Puzzle } from "@/db/models";
import { blogPostOps } from "@/db/operations";
import { logger } from "@/lib/logger";
import { getPuzzleType } from "@/lib/puzzleUtils";

function archiveDateFromPublished(publishedAt: Date): BlogArchiveDate {
  const d = new Date(publishedAt);
  return {
    year: d.getUTCFullYear(),
    month: d.getUTCMonth() + 1,
    day: d.getUTCDate(),
  };
}

function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 80);
}

async function ensureUniqueSlug(base: string, puzzleId: string): Promise<string> {
  let slug = base || `puzzle-${puzzleId.slice(0, 8)}`;
  let attempt = 0;
  while (attempt < 8) {
    const existing = await blogPostOps.findBySlug(slug);
    if (!existing || existing.puzzleId === puzzleId) {
      return slug;
    }
    attempt += 1;
    slug = `${base}-${attempt + 1}`;
  }
  return `${base}-${puzzleId.slice(0, 8)}`;
}

export type PersistPuzzleBlogResult =
  | { success: true; skipped: "already_exists"; puzzleId: string; postId: string }
  | { success: true; postId: string; puzzleId: string; title: string; slug: string }
  | { success: false; error: string; puzzleId?: string };

/**
 * Generate (via Eve blog skill) and insert a blog post for the given puzzle.
 * Idempotent on puzzleId — skips if a post already exists.
 */
export async function persistBlogForPuzzle(puzzle: Puzzle): Promise<PersistPuzzleBlogResult> {
  if (!puzzle?.id || !puzzle.answer) {
    return { success: false, error: "invalid_puzzle" };
  }

  const existing = await blogPostOps.findByPuzzleId(puzzle.id);
  if (existing) {
    return {
      success: true,
      skipped: "already_exists",
      puzzleId: puzzle.id,
      postId: existing.id,
    };
  }

  logger.info("Generating Eve blog post for puzzle", {
    puzzleId: puzzle.id,
    publishedAt: puzzle.publishedAt,
  });

  const generated = await generateBlogPost({
    puzzle: puzzle.puzzle ?? puzzle.rebusPuzzle,
    rebusPuzzle: puzzle.rebusPuzzle,
    puzzleType: puzzle.puzzleType,
    answer: puzzle.answer,
    difficulty: puzzle.difficulty,
    category: puzzle.category,
    explanation: puzzle.explanation,
    publishedAt: puzzle.publishedAt,
    hints: puzzle.hints,
    metadata: puzzle.metadata,
  });
  const puzzleType = getPuzzleType({
    puzzle: puzzle.puzzle ?? puzzle.rebusPuzzle,
    rebusPuzzle: puzzle.rebusPuzzle,
    puzzleType: puzzle.puzzleType,
    metadata: puzzle.metadata,
  });
  const baseSlug = slugify(generated.slug || generated.title);
  const slug = await ensureUniqueSlug(baseSlug, puzzle.id);
  const publishedAt = puzzle.publishedAt ? new Date(puzzle.publishedAt) : new Date();
  const now = new Date();

  const newBlogPost: NewBlogPost = {
    id: crypto.randomUUID(),
    title: generated.title,
    slug,
    content: generated.content,
    excerpt: generated.excerpt,
    authorId: "eve-ai",
    puzzleId: puzzle.id,
    publishedAt: now,
    createdAt: now,
    updatedAt: now,
    sections: generated.sections,
    seoMetadata: generated.seoMetadata,
    puzzleOrigin: {
      type: "ai-generated",
      inspiration: puzzle.explanation,
      creatorNotes: `Auto-generated by Eve from puzzle ${puzzle.id}`,
    },
    archiveDate: archiveDateFromPublished(publishedAt),
    puzzleType,
  };

  const saved: BlogPost = await blogPostOps.create(newBlogPost);

  revalidateTag("blog-posts", "max");
  revalidateTag("blog-posts-list", "max");
  revalidateTag("blog-archive", "max");
  revalidateTag("blog-posts-all", "max");

  logger.info("Eve blog post persisted", {
    blogId: saved.id,
    puzzleId: puzzle.id,
    title: saved.title,
    slug: saved.slug,
    hasSections: Boolean(saved.sections),
  });

  return {
    success: true,
    postId: saved.id,
    puzzleId: puzzle.id,
    title: saved.title,
    slug: saved.slug,
  };
}
