/**
 * Generate a puzzle archive post and open a reviewable GitHub pull request.
 * The post is published only after the PR is merged and deployed.
 */

import { type GeneratedBlogPost, generateBlogPost } from "@/ai/services/blog-generator";
import type { Puzzle } from "@/db/models";
import { getCollection } from "@/db/mongodb";
import { blogPostOps } from "@/db/operations";
import {
  type RepositoryBlogPostFile,
  repositoryBlogPostFileSchema,
} from "@/lib/blog/repository-posts";
import {
  type BlogPullRequestSkipped,
  createBlogPostPullRequest,
} from "@/lib/github/github-blog-pr";
import { logger } from "@/lib/logger";
import { getPuzzleDisplay, getPuzzleType } from "@/lib/puzzleUtils";

interface BlogProposalRecord {
  id: string;
  puzzleId: string;
  slug: string;
  branch: string;
  pullRequestNumber?: number;
  pullRequestUrl?: string;
  createdAt: Date;
  updatedAt: Date;
}

export type ProposePuzzleBlogResult =
  | {
      success: true;
      skipped: "already_exists" | "proposal_exists" | BlogPullRequestSkipped;
      puzzleId: string;
      postId?: string;
      pullRequestNumber?: number;
      pullRequestUrl?: string;
      branch?: string;
    }
  | {
      success: true;
      puzzleId: string;
      title: string;
      slug: string;
      pullRequestNumber: number;
      pullRequestUrl: string;
      branch: string;
      draft: boolean;
    }
  | { success: false; error: string; puzzleId?: string };

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^\w\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 90);
}

export function createRepositoryBlogPost(
  puzzle: Puzzle,
  generated: GeneratedBlogPost
): RepositoryBlogPostFile {
  const publishedAt = puzzle.publishedAt ? new Date(puzzle.publishedAt) : new Date();
  const dateKey = publishedAt.toISOString().slice(0, 10);
  const slug = slugify(`${generated.slug || generated.title}-${dateKey}`);
  const puzzleLike = {
    puzzle: puzzle.puzzle ?? puzzle.rebusPuzzle,
    rebusPuzzle: puzzle.rebusPuzzle,
    puzzleType: puzzle.puzzleType,
    metadata: puzzle.metadata,
  };
  const puzzleType = getPuzzleType(puzzleLike);
  const display = getPuzzleDisplay(puzzleLike, puzzleType);

  return repositoryBlogPostFileSchema.parse({
    version: 1,
    slug,
    title: generated.title,
    excerpt: generated.excerpt,
    content: generated.content,
    publishedAt: publishedAt.toISOString(),
    puzzle: {
      id: puzzle.id,
      display,
      type: puzzleType,
      answer: puzzle.answer,
      explanation: puzzle.explanation || "A visual word puzzle.",
      difficulty: puzzle.difficulty,
      category: puzzle.category,
    },
    sections: generated.sections,
    seoMetadata: generated.seoMetadata,
    puzzleOrigin: {
      type: "ai-generated",
      inspiration: puzzle.explanation,
      creatorNotes: `Generated by Eve from puzzle ${puzzle.id}`,
    },
  });
}

export async function proposeBlogForPuzzle(
  puzzle: Puzzle,
  editedPost?: GeneratedBlogPost
): Promise<ProposePuzzleBlogResult> {
  if (!puzzle?.id || !puzzle.answer) {
    return { success: false, error: "invalid_puzzle" };
  }

  const existingPost = await blogPostOps.findByPuzzleId(puzzle.id);
  if (existingPost) {
    return {
      success: true,
      skipped: "already_exists",
      puzzleId: puzzle.id,
      postId: existingPost.id,
    };
  }

  const proposals = getCollection<BlogProposalRecord>("blogPostProposals");
  const existingProposal = await proposals.findOne({ puzzleId: puzzle.id });
  if (existingProposal) {
    return {
      success: true,
      skipped: "proposal_exists",
      puzzleId: puzzle.id,
      pullRequestNumber: existingProposal.pullRequestNumber,
      pullRequestUrl: existingProposal.pullRequestUrl,
      branch: existingProposal.branch,
    };
  }

  logger.info("Generating Eve blog pull request", {
    puzzleId: puzzle.id,
    publishedAt: puzzle.publishedAt,
    edited: Boolean(editedPost),
  });

  const generated =
    editedPost ||
    (await generateBlogPost({
      puzzle: puzzle.puzzle ?? puzzle.rebusPuzzle,
      rebusPuzzle: puzzle.rebusPuzzle,
      puzzleType: puzzle.puzzleType,
      answer: puzzle.answer,
      difficulty: puzzle.difficulty,
      category: puzzle.category,
      explanation: puzzle.explanation,
      publishedAt: puzzle.publishedAt,
      hints: puzzle.hints,
      metadata: puzzle.metadata,
    }));
  const repositoryPost = createRepositoryBlogPost(puzzle, generated);
  const serialized = `${JSON.stringify(repositoryPost, null, 2)}\n`;
  const pullRequest = await createBlogPostPullRequest({
    slug: repositoryPost.slug,
    title: repositoryPost.title,
    puzzleId: puzzle.id,
    publishedAt: repositoryPost.publishedAt,
    content: serialized,
  });

  const now = new Date();
  await proposals.updateOne(
    { puzzleId: puzzle.id },
    {
      $set: {
        slug: repositoryPost.slug,
        branch: pullRequest.branch,
        pullRequestNumber: pullRequest.pullRequestNumber,
        pullRequestUrl: pullRequest.pullRequestUrl,
        updatedAt: now,
      },
      $setOnInsert: {
        id: crypto.randomUUID(),
        puzzleId: puzzle.id,
        createdAt: now,
      },
    },
    { upsert: true }
  );

  if ("skipped" in pullRequest) {
    return {
      success: true,
      skipped: pullRequest.skipped,
      puzzleId: puzzle.id,
      pullRequestNumber: pullRequest.pullRequestNumber,
      pullRequestUrl: pullRequest.pullRequestUrl,
      branch: pullRequest.branch,
    };
  }

  logger.info("Eve blog pull request opened", {
    puzzleId: puzzle.id,
    slug: repositoryPost.slug,
    pullRequestNumber: pullRequest.pullRequestNumber,
    pullRequestUrl: pullRequest.pullRequestUrl,
  });

  return {
    success: true,
    puzzleId: puzzle.id,
    title: repositoryPost.title,
    slug: repositoryPost.slug,
    pullRequestNumber: pullRequest.pullRequestNumber,
    pullRequestUrl: pullRequest.pullRequestUrl,
    branch: pullRequest.branch,
    draft: pullRequest.draft,
  };
}
